### ISSUE TITLE
[BUG] 일정 수정 누르고 x를 누를 때 일정 삭제를 권유

### ISSUE THREAD

**Issue by skfotakf** [wafflestudio20-5/team9-server#67]
![image](https://user-images.githubusercontent.com/86216809/216855929-759a5fa6-05cf-49c8-aabc-8ad4d782d8fb.png)
![image](https://user-images.githubusercontent.com/86216809/216855973-df3ae703-59d0-4d52-b66b-0ce64ed5d0bc.png)
제목에서 나오는 바와 같이 첫번째 사진에서 일정 수정을 취소하려고 x를 누르니까 삭제를 묻고 있습니다.
저는 해당 페이지를 나오려고 한거 뿐이고, 보통 그 상황에서 삭제를 묻지는 않는거 같아요.
일정 삭제 버튼은 저장 버튼 옆에 만드는게 더 좋을거 같아요

**Comment by fivessun5** [comment]
이건 버그가 아니고 서비스 개발자의 선택사항인 것 같습니다..!
그리고 토이프로젝트의 기본 목표인 클론코딩의 관점에서 보았을때도, 구글 캘린더 역시 일정 생성 도중 페이지를 이탈하려 할때 같은 형식의 메시지를 띄워주면서, 작성을 계속할지에 대해 확인 절차를 밟고 있습니다.

따라서 위 이슈는 버그가 아닌 의도된 결과이므로 이슈를 닫도록 하겠습니다 
<img width="393" alt="스크린샷 2023-02-06 오전 11 36 21" src="https://user-images.githubusercontent.com/104759605/216870501-2164381e-5f25-4039-b06f-7501d8e77c4d.png">
