### ISSUE TITLE
소셜로그인 후 다시 소셜로그인 시 버그 

### ISSUE THREAD

**Issue by kk0in** [wafflestudio20-5/team9-server#80]
소셜 로그인 후, 로그아웃 후 다시 소셜 로그인을 누르면, 카카오 계정과 비밀번호를 입력하지 않아도 자동으로 로그인이 되는 버그가 있습니다.

**Comment by fivessun5** [comment]
이건 해당 브라우저에 카카오 로그인 정보가 남아있기 때문입니다. 로그아웃 버튼은 저희 서비스에 대한 로그아웃 기능이지 카카오 어카운트에 대한 로그아웃 기능이 아니므로, 해당 브라우저를 종료하고 재시작 하거나, 따로 소셜 플랫폼에서 로그아웃 해주셔야 합니다.
